### ISSUE TITLE
server start bson issue

### ISSUE THREAD

**Issue by ozgurozden** [ValueMelody/melody-auth#129]
Hi,

Using Mac and getting error when dev or prod start with wrangler 

npm run dev:start  

> dev:start
> wrangler dev src/index.tsx

 ⛅️ wrangler 3.72.3
-------------------

▲ [WARNING] Enabling Wrangler compile-time Node.js compatibility polyfill mode for builtins and globals. This is experimental and has serious tradeoffs.

Using vars defined in .dev.vars
Your worker has access to the following bindings: 

[ERROR] Could not resolve "./win32/x64/bson"

    ../node_modules/mongodb/node_modules/bson/ext/index.js:5:17:
      5 │   bson = require('./win32/x64/bson');  
        ╵                  ~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./win32/ia32/bson"

    ../node_modules/mongodb/node_modules/bson/ext/index.js:7:17:
      7 │   bson = require('./win32/ia32/bson');  
        ╵                  ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../build/Release/bson"

    ../node_modules/mongodb/node_modules/bson/ext/index.js:9:17:
      9 │   bson = require('../build/Release/bson');  
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./win32/x64/bson"

    node_modules/shared/node_modules/bson/ext/index.js:5:17:
      5 │   bson = require('./win32/x64/bson');  
        ╵                  ~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./win32/ia32/bson"

    node_modules/shared/node_modules/bson/ext/index.js:7:17:
      7 │   bson = require('./win32/ia32/bson');  
        ╵                  ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../build/Release/bson"

    node_modules/shared/node_modules/bson/ext/index.js:9:17:
      9 │   bson = require('../build/Release/bson');  
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by byn9826** [comment]
Sorry, there was one step missing in the readme
For local dev env
```
git clone git@github.com:ValueMelody/melody-auth.git
cd melody-auth
npm install
npm run build # This is the missing step

cd server
cp dev.vars.example dev.vars # Your email functionality related env vars should be put here
npm run dev:secret:generate
npm run dev:migration:apply
npm run dev:start
```

I guess you did something like `npm install shared`. The"shared" module will be generated by `npm run build`, it's not a npm package

**Comment by byn9826** [comment]
> Dear byn9286,
> 
> I would like to extend my sincere gratitude for sharing this remarkable project. Your work is truly outstanding and has made a significant impression on me. Such contributions are both inspiring and immensely valuable.
> 
> I am pleased to inform you that the issue I previously mentioned has been resolved. Thank you for your prompt response. Although I had already executed the npm run build command initially without success, I re-downloaded the repository and started from scratch, which successfully resolved the issue. I greatly appreciate your swift assistance.
> 
> It is a pleasure to support and exchange ideas with you on this project. Should you require any further assistance or feedback, please do not hesitate to reach out.
> 
> Once again, congratulations on your excellent work, and I wish you continued success in all your endeavors.
> 
> Best regards,

Thank you! Having people test and use this project is a great motivation for me.
