### ISSUE TITLE
The command npm run prod:secret:generate fails to execute in a proxy environment.

### ISSUE THREAD

**Issue by shydow** [ValueMelody/melody-auth#184]
Problem Analysis: 

On line 104 of [melody-auth/server/src/scripts/generate-secret.cjs]:

the command [wrangler kv key list --prefix=sessionSecret --binding=KV ${condition}] is causing an issue when executed in a proxy environment. 

The first line of the output indicates that a proxy environment has been detected: "Proxy environment variables detected. We'll use your proxy for fetch requests."

**Comment by byn9826** [comment]
Can you indicate what is your exact env? OS, node version, etc

**Comment by shydow** [comment]
OS: ubuntu 24.04 LTS
node version: v22.9.0
browser: chrome

**Comment by byn9826** [comment]
Can you paste all the outputs? "Use proxy for fetch requests" doesn't looks like the cause of the issue.

Also "prod:secret:generate" is storing value to Cloudflare KV, have you logged into Cloudflare through cli and replaced kv id in wrangler with your own kv id? Have you encouter any issue with "dev:secret:generate" or "node:secret:generate"?

**Comment by byn9826** [comment]
Looks similar to https://github.com/cloudflare/workers-sdk/issues/4515. In a proxy env, wrangler will output this extra message, which messed the expected output format.

By proxy env, are you using a vpn or something?

**Comment by shydow** [comment]
> Looks similar to [cloudflare/workers-sdk#4515](https://github.com/cloudflare/workers-sdk/issues/4515). In a proxy env, wrangler will output this extra message, which messed the expected output format.

yes, you are right. 

> 
> By proxy env, are you using a vpn or something?

I use the proxy by setting the environment variable 
```
export HTTP_PROXY=xxxx
```

**Comment by byn9826** [comment]
Check if #185 fix your issue

**Comment by shydow** [comment]
Excellent work. The bug has been successfully resolved.
