### ISSUE TITLE
Is it possible to deploy an admin-panel using Cloudflare Pages?

### ISSUE THREAD

**Issue by shydow** [ValueMelody/melody-auth#190]
Would it be possible to include this information in the documentation? Thank you.

**Comment by byn9826** [comment]
The admin-panel is a full stack nextjs app, so it is not possible to deploy it as a normal react app using Cloudflare pages.

It might be possible to deploy it using the edge support of pages, however that will at least require replacement of some dependencies, which is not something on my plan for the near future

**Comment by byn9826** [comment]
Deploy admin-panel to cloudflare workers is supported through an experimental library now.
https://auth.valuemelody.com/admin-panel.html#experimental-deploy-admin-panel-to-cloudflare-workers

In this case, there will be no supported for deploy admin-panel to Cloudflare pages in this project
