### ISSUE TITLE
Server-side auth

### ISSUE THREAD

**Issue by jepezi** [ValueMelody/melody-auth#196]
Hi! First of all, thanks so much for this awesome project. I'm wondering if it's possible to check auth/ session server side? I see the code in admin-panel uses client side react-sdk. Thanks!

**Comment by byn9826** [comment]
Thanks.
For server side auth, it's more or less moving the token storage part from localStorage/sessionStorage to cookies/session, so you should technically be able to use any server side auth library that support customizing OAuth provider config to achieve it.
I may add an example or package for this in the future, but no timeline on this.

**Comment by byn9826** [comment]
Basic example added for using next-auth
https://github.com/ValueMelody/melody-auth/blob/main/examples/next-auth-js-example/src/app/api/auth/%5B...nextauth%5D/route.ts
